// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDtoEJdW2PcOm-H1qpU3U8kWdULmvoguw',
    appId: '1:171820089623:web:f3cea357cf96d74a8cf752',
    messagingSenderId: '171820089623',
    projectId: 'build-wise-5e956',
    authDomain: 'build-wise-5e956.firebaseapp.com',
    storageBucket: 'build-wise-5e956.firebasestorage.app',
    measurementId: 'G-JVKVKXBGX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmEwF3Yedl7juOWmndvEti8HGVBVYY7Co',
    appId: '1:171820089623:android:c3a96bdc4a79d1ca8cf752',
    messagingSenderId: '171820089623',
    projectId: 'build-wise-5e956',
    storageBucket: 'build-wise-5e956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdBm5Yae_MVXcqgO7_lUUJq454fZZwHkE',
    appId: '1:171820089623:ios:46fdab4380368a7c8cf752',
    messagingSenderId: '171820089623',
    projectId: 'build-wise-5e956',
    storageBucket: 'build-wise-5e956.firebasestorage.app',
    iosBundleId: 'com.buildwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdBm5Yae_MVXcqgO7_lUUJq454fZZwHkE',
    appId: '1:171820089623:ios:58a3551b1ffd3f058cf752',
    messagingSenderId: '171820089623',
    projectId: 'build-wise-5e956',
    storageBucket: 'build-wise-5e956.firebasestorage.app',
    iosBundleId: 'com.buildwise.buildWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDtoEJdW2PcOm-H1qpU3U8kWdULmvoguw',
    appId: '1:171820089623:web:21a45c4b87a0cc6b8cf752',
    messagingSenderId: '171820089623',
    projectId: 'build-wise-5e956',
    authDomain: 'build-wise-5e956.firebaseapp.com',
    storageBucket: 'build-wise-5e956.firebasestorage.app',
    measurementId: 'G-J9DNX14R02',
  );
}
